version: "3.9"
services:
    postgres:
        image: postgres:14.2
        environment:
            POSTGRES_DB: "studs"
            POSTGRES_USER: "s407959"
            POSTGRES_PASSWORD: "R3JIQIhNsdM2QGJv"
        ports:
            - "5432:5432"
