BEGIN;

CREATE TYPE sex AS ENUM ('man', 'woman');

CREATE TYPE entity AS ENUM (
	'ship',
	'astronaut',
	'planet',
	'equipment',
	'mission'
);

CREATE TABLE SHIP (
	SHIP_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LAUNCH_DATE DATE NOT NULL,
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'maintenance'))
);

CREATE TABLE ASTRONAUT (
	ASTRONAUT_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	STATUS VARCHAR(20) CHECK (STATUS IN ('onboard', 'retired')),
	POSITION VARCHAR(50) NOT NULL,
	SHIP_ID INT NOT NULL REFERENCES SHIP (SHIP_ID)
);

CREATE TABLE PLANET (
	PLANET_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	TYPE VARCHAR(20) CHECK (TYPE IN ('star', 'planet')),
	DISTANCE FLOAT NOT NULL
);

CREATE TABLE COMMUNICATION (
	COMMUNICATION_ID SERIAL PRIMARY KEY,
	SHIP_ID INT NOT NULL UNIQUE REFERENCES SHIP (SHIP_ID),
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'interrupted')),
	LAST_CHECK TIMESTAMP
);

CREATE TABLE ALERT (
	ALERT_ID SERIAL PRIMARY KEY,
	COMMUNICATION_ID INT NOT NULL REFERENCES COMMUNICATION (COMMUNICATION_ID),
	ASTRONAUT_ID INT NOT NULL REFERENCES ASTRONAUT (ASTRONAUT_ID),
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'resolved')),
	TYPE VARCHAR(20) CHECK (TYPE IN ('commun-failure', 'threat')),
	TIME TIMESTAMP NOT NULL
);

CREATE TABLE SHIPPOSITION (
	POSITION_ID SERIAL PRIMARY KEY,
	SHIP_ID INT NOT NULL REFERENCES SHIP (SHIP_ID),
	PLANET_ID INT NOT NULL REFERENCES PLANET (PLANET_ID),
	TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE MISSION (
	MISSION_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	START_DATE DATE NOT NULL
);

CREATE TABLE EQUIPMENT (
	EQUIPMENT_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	TYPE VARCHAR(20) CHECK (TYPE IN ('laser', 'двигатель')),
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'broken'))
);

CREATE TABLE MISSIONASSIGNMENT (
	ASSIGNMENT_ID SERIAL PRIMARY KEY,
	ASTRONAUT_ID INT NOT NULL REFERENCES ASTRONAUT (ASTRONAUT_ID),
	MISSION_ID INT NOT NULL REFERENCES MISSION (MISSION_ID),
	ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE EQUIPMENTSTATUS (
	STATUS_ID SERIAL PRIMARY KEY,
	EQUIPMENT_ID INT NOT NULL REFERENCES EQUIPMENT (EQUIPMENT_ID),  
	STATUS VARCHAR(20),
	TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE MISSIONPHASE (
	PHASE_ID SERIAL PRIMARY KEY,
	MISSION_ID INT REFERENCES MISSION (MISSION_ID),
	PHASE_NAME VARCHAR(50),
	STATUS VARCHAR(20) CHECK (STATUS IN ('planned', 'in_progress', 'completed'))
);


INSERT INTO
	SHIP (NAME, LAUNCH_DATE, STATUS)
VALUES
	('Дискавери', '2024-02-14', 'active');
	
INSERT INTO
	MISSION (TITLE, DESCRIPTION, START_DATE)
VALUES
	(
		'Исследование Солнца',
		'Анализ солнечной активности',
		'2025-02-16'
	);

INSERT INTO
	EQUIPMENT (NAME, TYPE, STATUS)
VALUES
	('Лазерный передатчик', 'laser', 'active');

INSERT INTO 
	ASTRONAUT (NAME, POSITION, STATUS, SHIP_ID)
VALUES
	('Дэвид Боумен', 'Командир', 'onboard', 1);

INSERT INTO
	MISSIONASSIGNMENT (ASTRONAUT_ID, MISSION_ID, ROLE)
VALUES
	(1, 1, 'Оператор связи');

INSERT INTO
	MISSIONPHASE (MISSION_ID, PHASE_NAME, STATUS)
VALUES
	(1, 'Подготовка к старту', 'completed');


INSERT INTO
	PLANET (NAME, TYPE, DISTANCE)
VALUES
	('Земля', 'planet', 0.0),
	('Солнце', 'star', 149.6);

INSERT INTO
	COMMUNICATION (SHIP_ID, STATUS, LAST_CHECK)
VALUES
	(1, 'active', '2024-02-15 13:00:00');

INSERT INTO
	ALERT (
		COMMUNICATION_ID,
		ASTRONAUT_ID,
		TIME,
		TYPE,
		STATUS
	)
VALUES
	(
		1,
		1,
		'2024-02-15 13:10:00',
		'commun-failure',
		'resolved'
	);

INSERT INTO
	SHIPPOSITION (SHIP_ID, PLANET_ID, TIMESTAMP)
VALUES
	(1, 1, '2024-02-15 09:00:00');

INSERT INTO
	EQUIPMENTSTATUS (EQUIPMENT_ID, STATUS, TIMESTAMP)
VALUES
	(1, 'active', '2024-02-16 12:00:00');

END;