BEGIN;
-- 为所有 DROP 命令添加 CASCADE 选项，自动解除依赖关系
DROP TABLE IF EXISTS ALERT CASCADE;

DROP TABLE IF EXISTS MISSIONASSIGNMENT CASCADE;

DROP TABLE IF EXISTS MISSIONPHASE CASCADE;

DROP TABLE IF EXISTS EQUIPMENTSTATUS CASCADE;

DROP TABLE IF EXISTS ASTRONAUT CASCADE;

DROP TABLE IF EXISTS SHIPPOSITION CASCADE;

DROP TABLE IF EXISTS COMMUNICATION CASCADE;

DROP TABLE IF EXISTS EQUIPMENT CASCADE;

DROP TABLE IF EXISTS MISSION CASCADE;

DROP TABLE IF EXISTS PLANET CASCADE;

DROP TABLE IF EXISTS SHIP CASCADE;

DROP TYPE IF EXISTS sex CASCADE;

CREATE TYPE sex AS ENUM ('man', 'woman');

CREATE TABLE SHIP (
	SHIP_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LAUNCH_DATE DATE NOT NULL,
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'maintenance'))
);

CREATE TABLE ASTRONAUT (
	ASTRONAUT_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	STATUS VARCHAR(20) CHECK (STATUS IN ('onboard', 'retired')),
	POSITION VARCHAR(50) NOT NULL,
	Sex sex NOT NULL,
	SHIP_ID INT NOT NULL REFERENCES SHIP (SHIP_ID)
);

CREATE TABLE PLANET (
	PLANET_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	TYPE VARCHAR(20) CHECK (TYPE IN ('star', 'planet')),
	DISTANCE FLOAT NOT NULL
);

CREATE TABLE COMMUNICATION (
	COMMUNICATION_ID SERIAL PRIMARY KEY,
	SHIP_ID INT NOT NULL UNIQUE REFERENCES SHIP (SHIP_ID),
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'interrupted')),
	LAST_CHECK TIMESTAMP
);

CREATE TABLE ALERT (
	ALERT_ID SERIAL PRIMARY KEY,
	COMMUNICATION_ID INT NOT NULL REFERENCES COMMUNICATION (COMMUNICATION_ID),
	ASTRONAUT_ID INT NOT NULL REFERENCES ASTRONAUT (ASTRONAUT_ID),
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'resolved')),
	TYPE VARCHAR(20) CHECK (TYPE IN ('commun-failure', 'threat')),
	TIME TIMESTAMP NOT NULL
);

CREATE TABLE SHIPPOSITION (
	POSITION_ID SERIAL PRIMARY KEY,
	SHIP_ID INT NOT NULL REFERENCES SHIP (SHIP_ID),
	PLANET_ID INT NOT NULL REFERENCES PLANET (PLANET_ID),
	TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE MISSION (
	MISSION_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	START_DATE DATE NOT NULL
);

CREATE TABLE EQUIPMENT (
	EQUIPMENT_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	TYPE VARCHAR(20) CHECK (TYPE IN ('laser', 'machine', 'quantum')),
	STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'broken', 'on-reserve'))
);

CREATE TABLE MISSIONASSIGNMENT (
	ASSIGNMENT_ID SERIAL PRIMARY KEY,
	ASTRONAUT_ID INT NOT NULL REFERENCES ASTRONAUT (ASTRONAUT_ID),
	MISSION_ID INT NOT NULL REFERENCES MISSION (MISSION_ID),
	ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE EQUIPMENTSTATUS (
	STATUS_ID SERIAL PRIMARY KEY,
	EQUIPMENT_ID INT NOT NULL REFERENCES EQUIPMENT (EQUIPMENT_ID),  
	STATUS VARCHAR(20),
	TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE MISSIONPHASE (
	PHASE_ID SERIAL PRIMARY KEY,
	MISSION_ID INT REFERENCES MISSION (MISSION_ID),
	PHASE_NAME VARCHAR(50),
	STATUS VARCHAR(20) CHECK (STATUS IN ('planned', 'in_progress', 'completed'))
);


INSERT INTO
	SHIP (NAME, LAUNCH_DATE, STATUS)
VALUES
	('Дискавери', '2024-02-14', 'active'),
	('Сентинел', '2024-02-27', 'active');
	
INSERT INTO
	MISSION (TITLE, DESCRIPTION, START_DATE)
VALUES
	(
		'Исследование Солнца',
		'Анализ солнечной активности',
		'2025-02-16'
	),
	(
		'Исследование Титана',
		'Исследование возможности метанового отстойника',
		'2025-07-25'
	),
	(
		'Исследование Урана',
		'Исследование ледникового покрова',
		'2026-05-26'
	);

INSERT INTO
	EQUIPMENT (NAME, TYPE, STATUS)
VALUES
	('Лазерный передатчик', 'laser', 'active'),
	('глубоководный бурильщик', 'machine', 'on-reserve'),
	('квантовый ретранслятор','quantum', 'broken');

INSERT INTO 
	ASTRONAUT (NAME, POSITION, STATUS, SEX, SHIP_ID)
VALUES
	('Дэвид Боумен', 'Командир', 'onboard', 'man', 1),
	('Ирина Волкова', 'астрофизик', 'onboard', 'woman', 1),
	('Раджив Сингх', 'инженер', 'onboard', 'man', 1),
	('Чжун Цзяцзюнь', 'инженер', 'onboard', 'man', 2),
	('Cy Лянхуа', 'доктор', 'onboard', 'man', 2);

INSERT INTO
	MISSIONASSIGNMENT (ASTRONAUT_ID, MISSION_ID, ROLE)
VALUES
	(1, 1, 'Оператор связи'),
	(2, 2, 'Исследование планетарной геологии'),
	(2, 3, 'Исследование ледникового покрова');
	
INSERT INTO
	MISSIONPHASE (MISSION_ID, PHASE_NAME, STATUS)
VALUES
	(1, 'Подготовка к старту', 'completed'),
	(2, 'Отъезд на Титан', 'planned');


INSERT INTO
	PLANET (NAME, TYPE, DISTANCE)
VALUES
	('Земля', 'planet', 0.0),
	('Солнце', 'star', 149.6),
	('Титан', 'planet', 158.0),
	('Уран', 'planet', 260.0);

INSERT INTO
	COMMUNICATION (SHIP_ID, STATUS, LAST_CHECK)
VALUES
	(1, 'active', '2024-02-15 13:00:00'),
	(2, 'active', '2024-04-25 15:00:00');

INSERT INTO
	ALERT (
		COMMUNICATION_ID,
		ASTRONAUT_ID,
		TIME,
		TYPE,
		STATUS
	)
VALUES
	(
		1,
		1,
		'2024-02-15 13:10:00',
		'commun-failure',
		'resolved'
	);

INSERT INTO
	SHIPPOSITION (SHIP_ID, PLANET_ID, TIMESTAMP)
VALUES
	(1, 1, '2024-02-15 09:00:00'),
	(1, 2, '2024-04-06 14:00:00');

INSERT INTO
	EQUIPMENTSTATUS (EQUIPMENT_ID, STATUS, TIMESTAMP)
VALUES
	(1, 'active', '2024-02-16 12:00:00'),
	(2, 'on reserve', '2024-05-13 12:00:00');

END;