BEGIN;

SELECT * FROM ASTRONAUT; -- 返回宇航员这一实体下的所有行

SELECT * FROM EQUIPMENT; -- 返回装备这一实体下的所有行

SELECT NAME FROM PLANET; -- 返回行星这一实体下的所有行的名称

UPDATE MISSION SET START_DATE = '2026-07-26' WHERE START_DATE = '2026-05-26'; -- 更新行星这一实体下的所有行的开始时间

SELECT START_DATE FROM MISSION; -- 返回所有任务开始时间

DELETE FROM ASTRONAUT WHERE ASTRONAUT_ID = 5; -- 删除宇航员这一实体下的ID为5的行

END;