BEGIN;

SELECT * FROM ASTRONAUT;

SELECT * FROM EQUIPMENT;

SELECT NAME FROM PLANET;

UPDATE MISSION SET START_DATE = '2026-07-26' WHERE START_DATE = '2026-05-26';

SELECT START_DATE FROM MISSION;

DELETE FROM ASTRONAUT WHERE ASTRONAUT_ID = 5;

END;