import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { composeReadme, manualContent } from './course-readme.mjs';
import { courseStatus, courseStatusSummary, labStatus, statusKeys } from './course-status.mjs';
import { backlinkPage } from './knowledge-links.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'navigation/catalog.json'), 'utf8'));
const check = process.argv.includes('--check');
const sections = { theory: '理论 · Теория', labs: '实验 / 作业 · Практика', defense: '答辩 · Защита', exam: '考试 · Экзамен', resources: '资料 / 速查 · Материалы' };
const generated = '<!-- Generated by tools/generate-index.mjs from navigation/catalog.json. Edit the catalog, not this page. -->';
const outputs = new Map();
const courseSources = new Map();
const problems = [];
const ids = new Set();
function safePath(file) {
  return typeof file === 'string' && file.length > 0 && !/[\\<>:"|?*]/.test(file) &&
    !path.posix.isAbsolute(file) && !path.win32.isAbsolute(file) &&
    !file.split('/').some(part => part === '..' || part === '.' || part === '');
}
function assertNoSymlink(file) {
  let current = root;
  for (const part of file.split('/')) {
    current = path.join(current, part);
    const stat = (() => { try { return fs.lstatSync(current); } catch (error) { if (error.code === 'ENOENT') return null; throw error; } })();
    if (stat?.isSymbolicLink()) {
      problems.push(`路径不可经过符号链接：${file}`);
      return false;
    }
  }
  return true;
}
// Course READMEs retain their hand-written body. All other outputs must carry
// the generated-page marker; validate destinations before writing anything.
for (const course of catalog.courses) {
  if (!safePath(course.directory)) problems.push(`无效课程目录：${course.directory}`);
  if (!statusKeys.includes(course.status) || Object.values(course.semesterStatus || {}).some(s => !statusKeys.includes(s))) problems.push(`无效课程状态：${course.id}`);
  if (!safePath(course.dashboard) || !course.dashboard.endsWith('/readme.md') ||
      !course.dashboard.startsWith(course.directory + '/')) problems.push(`无效课程 README 路径：${course.dashboard}`);
}
const semesterNumbers = new Set();
for (const semester of catalog.semesters) {
  if (!Number.isInteger(semester.number) || semester.number < 1 || semesterNumbers.has(semester.number)) problems.push(`无效或重复学期：${semester.number}`);
  semesterNumbers.add(semester.number);
}
if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
function link(from, label, target) {
  const [file, anchor] = target.split('#');
  const relative = path.posix.relative(path.posix.dirname(from), file) || '.';
  return `[${label}](${relative.split('/').map(encodeURIComponent).join('/')}${anchor ? '#' + anchor : ''})`;
}
function save(file, body) {
  if (!safePath(file)) { problems.push(`输出路径超出允许范围：${file}`); return; }
  if (outputs.has(file)) problems.push(`输出页面重复：${file}`);
  outputs.set(file, `${generated}\n\n${body.trim()}\n`);
}
function semesterLinks(from, course) {
  return course.semesters.map(n => link(from, `第 ${n} 学期`, `academic/semester-${String(n).padStart(2, '0')}.md`)).join(' · ');
}
function categoryLink(from, course, type) {
  const entries = course.resources[type] || [];
  return entries.length ? link(from, `${entries.length} 个入口`, course.dashboard + '#' + type) : '—';
}

for (const course of catalog.courses) {
  if (ids.has(course.id)) problems.push(`重复课程 id：${course.id}`);
  ids.add(course.id);
  if (!fs.existsSync(path.join(root, course.directory))) problems.push(`课程目录不存在：${course.directory}`);
  for (const number of course.semesters) {
    if (!catalog.semesters.some(s => s.number === number)) problems.push(`未知学期：${course.id} / ${number}`);
  }
  for (const [type, entries] of Object.entries(course.resources)) {
    if (!(type in sections)) problems.push(`未知资料类型：${course.id} / ${type}`);
    for (const entry of entries) {
      if (!entry.label || !safePath(entry.path)) problems.push(`无效资源：${course.id} / ${entry.path}`);
      else if (!fs.existsSync(path.join(root, entry.path))) problems.push(`资源不存在：${entry.path}`);
    }
  }
  const from = course.dashboard;
  if (!assertNoSymlink(from)) continue;
  const absolute = path.join(root, from);
  if (fs.existsSync(absolute) && !fs.statSync(absolute).isFile()) {
    problems.push(`课程 README 不是文件：${from}`); continue;
  }
  const source = fs.existsSync(absolute) ? fs.readFileSync(absolute, 'utf8') : null;
  courseSources.set(from, source);
  const related = (course.related || []).map(id => {
    const c = catalog.courses.find(c => c.id === id);
    if (!c) problems.push(`关联课程不存在：${course.id} → ${id}`);
    return c;
  }).filter(Boolean);
  if (outputs.has(from)) problems.push(`输出页面重复：${from}`);
  try { outputs.set(from, composeReadme(source || '', course, sections, link, semesterLinks, related)); }
  catch (error) { problems.push(`${from}: ${error.message}`); }
}

for (const semester of catalog.semesters) {
  const from = `academic/semester-${String(semester.number).padStart(2, '0')}.md`;
  const courses = catalog.courses.filter(c => c.semesters.includes(semester.number));
  const previous = catalog.semesters.find(s => s.number === semester.number - 1);
  const next = catalog.semesters.find(s => s.number === semester.number + 1);
  const adjacent = [link(from, '学期总览', 'navigation/index.md'), previous && link(from, '上一学期', `academic/semester-${String(previous.number).padStart(2, '0')}.md`), next && link(from, '下一学期', `academic/semester-${String(next.number).padStart(2, '0')}.md`)].filter(Boolean).join(' · ');
  const rows = courses.map(c => `| ${link(from, c.title, c.dashboard)} | ${c.ru} | ${c.assessments?.[semester.number] || '见课程资料'} | ${courseStatus(c, semester.number)} | ${categoryLink(from, c, 'labs')} | ${categoryLink(from, c, 'exam')} |`).join('\n');
  save(from, `# 第 ${semester.number} 学期 · ${semester.title}\n\n${adjacent}\n\n${semester.period} · 大${semester.year === 1 ? '一' : semester.year === 2 ? '二' : '三'}。本页 ${courses.length} 门课程已有仓库资料。\n\n按学期查看课程、实验与考试资料。第 1–4 学期的课程与实验均已通过；第 5 学期按当前记录维护。\n\n| 课程 | Русское название | 考核类型 | 状态 | 实验 / 作业 | 考试资料 |\n|---|---|---|---|---|---|\n${rows}\n\n${link(from, '本学期考前复习入口', 'study/revision.md')} · ${link(from, '实验答辩入口', 'study/defense.md')}`);
}

const overview = 'navigation/index.md';
save(overview, `# 学期导航 · Учебные семестры\n\n${link(overview, '首页', 'README.md')} · ${link(overview, '全部课程', 'navigation/courses.md')} · ${link(overview, '复习脑图', 'knowledge/mindmap.md')}\n\n| 学年 | 学期 | 时间 | 课程数 | 状态 |\n|---|---|---|---|---|\n${catalog.semesters.map(s => `| 第 ${s.year} 学年 | ${link(overview, `第 ${s.number} 学期 · ${s.title}`, `academic/semester-${String(s.number).padStart(2, '0')}.md`)} | ${s.period} | ${catalog.courses.filter(c => c.semesters.includes(s.number)).length} | ${s.number < 5 ? '✓ 已通过' : '— 未标记'} |`).join('\n')}\n\n第 1–4 学期已通过，第 5 学期为当前学习阶段。跨学期课程共用一份课程 README。\n\n${link(overview, '知识地图', 'knowledge/index.md')} · ${link(overview, '资料反向关联', 'knowledge/backlinks.md')} · ${link(overview, '阅读指南', 'navigation/reading.md')}`);
const all = 'navigation/courses.md';
save(all, `# 课程总览 · Курсы\n\n${link(all, '首页', 'README.md')} · ${link(all, '按学期浏览', 'navigation/index.md')} · ${link(all, '知识地图', 'knowledge/index.md')} · ${link(all, '复习脑图', 'knowledge/mindmap.md')}\n\n${catalog.courses.filter(c => c.status === 'passed').length} 门归档课程 · ${catalog.courses.filter(c => c.semesters.includes(5)).length} 门当前课程。每门课程使用唯一 README，将讲义、实验、答辩与考试资料放在同一入口。\n\n## 当前学期\n\n| 课程 | 状态 | 理论 | 实验 / 作业 | 答辩 | 考试 |\n|---|---|---|---|---|---|\n${catalog.courses.filter(c => c.semesters.includes(5)).map(c => `| ${link(all, c.title, c.dashboard)} | ${courseStatus(c, 5)} | ${categoryLink(all, c, 'theory')} | ${categoryLink(all, c, 'labs')} | ${categoryLink(all, c, 'defense')} | ${categoryLink(all, c, 'exam')} |`).join('\n')}\n\n## 大一、大二 · 已通过\n\n| 课程 | 学期 | 状态 | 理论 | 实验 / 作业 | 答辩 | 考试 |\n|---|---|---|---|---|---|---|\n${catalog.courses.filter(c => c.semesters.some(n => n < 5)).map(c => `| ${link(all, c.title, c.dashboard)} | ${c.semesters.filter(n => n < 5).join('、')} | ✓ 已通过 | ${categoryLink(all, c, 'theory')} | ${categoryLink(all, c, 'labs')} | ${categoryLink(all, c, 'defense')} | ${categoryLink(all, c, 'exam')} |`).join('\n')}\n\n## 补充学习\n\n${link(all, 'Java 基础与练习', 'Java/Note.md')} · ${link(all, 'Java 专题', 'Java/subtopi.md')} · ${link(all, 'Go 源码', 'Go')} · ${link(all, '预科数学语言', 'MathsLanguage/keyknowledge.md')} · ${link(all, 'Helios 使用', 'helios.md')}`);
const labs = 'navigation/labs.md';
save(labs, `# 实验与作业索引 · Практические работы\n\n${link(labs, '首页', 'README.md')} · ${link(labs, '答辩指南', 'study/defense.md')} · ${link(labs, '课程总览', 'navigation/courses.md')}\n\n第 1–4 学期的课程与实验均已通过；当前学期使用 ✓ 已通过 / ○ 待通过 / — 未标记。实验编号、报告与源码版本沿用原目录。\n\n${catalog.courses.filter(c => c.resources.labs?.length).map(c => {
  const manual = manualContent(outputs.get(c.dashboard), c.dashboard);
  return `## ${c.title}\n\n${link(labs, '课程入口', c.dashboard)} · ${courseStatusSummary(c)}\n\n| 实验 / 作业 | 状态 |\n|---|---|\n${c.resources.labs.map(e => `| ${link(labs, e.label, e.path)} | ${labStatus(c, e, manual)} |`).join('\n')}`;
}).join('\n\n')}`);
const mindmap = 'knowledge/mindmap.md';
const routes = [
  ['数学与建模', ['linear-algebra', 'analysis', 'discrete', 'extra-analysis', 'probability', 'complex', 'physics', 'numerical', 'statistics', 'optimization', 'modeling']],
  ['编程与计算机系统', ['informatics', 'opd', 'programming', 'languages', 'algorithms', 'architecture', 'os']],
  ['数据与软件工程', ['database', 'web', 'opi', 'information-systems', 'software-architecture', 'ui']],
  ['人工智能与可视化', ['ai', 'graphics', 'knowledge-graphs']],
  ['语言与表达', ['russian', 'history', 'presentation']]
];
save(mindmap, `# 复习脑图\n\n${link(mindmap, '首页', 'README.md')} · ${link(mindmap, '知识关系图', 'knowledge/index.md')} · ${link(mindmap, '资料反向关联', 'knowledge/backlinks.md')}\n\n按学习方向展开课程，沿着课程进入理论、速查与答辩。网站提供可折叠、缩放的 Markmap 脑图；VS Code 和 GitHub 可直接阅读下面的大纲。\n\n${routes.map(([title, ids]) => `## ${title}\n\n${ids.map(id => {
  const c = catalog.courses.find(c => c.id === id);
  const quick = c.resources.resources?.find(e => /(?:quick-review|cheatsheet)\.md$/.test(e.path));
  const entry = quick || c.resources.defense?.[0] || c.resources.theory?.[0] || c.resources.labs?.[0];
  return `- ${link(mindmap, c.title, c.dashboard)} · ${courseStatusSummary(c)}${entry ? `\n  - ${link(mindmap, entry.label, entry.path)}` : ''}`;
}).join('\n')}`).join('\n\n')}\n`);
save('knowledge/backlinks.md', backlinkPage(root, catalog, outputs, link));

for (const file of outputs.keys()) {
  if (!assertNoSymlink(file)) continue;
  const absolute = path.join(root, file);
  if (courseSources.has(file)) {
    const source = fs.existsSync(absolute) ? fs.readFileSync(absolute, 'utf8') : null;
    if (source !== courseSources.get(file)) problems.push(`课程 README 已变更，请重新运行：${file}`);
  } else if (fs.existsSync(absolute) && (!fs.statSync(absolute).isFile() || !fs.readFileSync(absolute, 'utf8').startsWith(generated))) {
    problems.push(`拒绝覆盖原始文件（缺少生成标记）：${file}`);
  }
}
if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
for (const [file, body] of outputs) {
  const absolute = path.join(root, file);
  if (check) {
    if (!fs.existsSync(absolute) || fs.readFileSync(absolute, 'utf8') !== body) problems.push(`需要重新生成：${file}`);
  } else {
    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    fs.writeFileSync(absolute, body);
  }
}
if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
console.log(`${check ? '已验证' : '已更新'} ${catalog.courses.length} 个课程 README 和 ${outputs.size - catalog.courses.length} 个导航页；${catalog.semesters.length} 个学期。`);
