import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'navigation/catalog.json'), 'utf8'));
const check = process.argv.includes('--check');
const sections = { theory: '理论 · Теория', labs: '实验 / 作业 · Практика', defense: '答辩 · Защита', exam: '考试 · Экзамен', resources: '资料 / 速查 · Материалы' };
const generated = '<!-- Generated by tools/generate-index.mjs from navigation/catalog.json. Edit the catalog, not this page. -->';
const outputs = new Map();
const problems = [];
const ids = new Set();
function safePath(file) {
  return typeof file === 'string' && file.length > 0 && !/[\\<>:"|?*]/.test(file) &&
    !path.posix.isAbsolute(file) && !path.win32.isAbsolute(file) &&
    !file.split('/').some(part => part === '..' || part === '.' || part === '');
}
function assertNoSymlink(file) {
  let current = root;
  for (const part of file.split('/')) {
    current = path.join(current, part);
    const stat = (() => { try { return fs.lstatSync(current); } catch (error) { if (error.code === 'ENOENT') return null; throw error; } })();
    if (stat?.isSymbolicLink()) {
      problems.push(`路径不可经过符号链接：${file}`);
      return false;
    }
  }
  return true;
}
// Validate all destinations before rendering or writing anything. A catalog typo
// must never turn an original note into a generated dashboard.
for (const course of catalog.courses) {
  if (!safePath(course.directory)) problems.push(`无效课程目录：${course.directory}`);
  if (!safePath(course.dashboard) || !course.dashboard.endsWith('/index.md') ||
      !course.dashboard.startsWith(course.directory + '/')) problems.push(`无效 Dashboard 路径：${course.dashboard}`);
}
const semesterNumbers = new Set();
for (const semester of catalog.semesters) {
  if (!Number.isInteger(semester.number) || semester.number < 1 || semesterNumbers.has(semester.number)) problems.push(`无效或重复学期：${semester.number}`);
  semesterNumbers.add(semester.number);
}
if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
function link(from, label, target) {
  const [file, anchor] = target.split('#');
  const relative = path.posix.relative(path.posix.dirname(from), file) || '.';
  return `[${label}](${relative.split('/').map(encodeURIComponent).join('/')}${anchor ? '#' + anchor : ''})`;
}
function save(file, body) {
  if (!safePath(file)) { problems.push(`输出路径超出允许范围：${file}`); return; }
  if (outputs.has(file)) problems.push(`输出页面重复：${file}`);
  outputs.set(file, `${generated}\n\n${body.trim()}\n`);
}
function semesterLinks(from, course) {
  return course.semesters.map(n => link(from, `第 ${n} 学期`, `academic/semester-${String(n).padStart(2, '0')}.md`)).join(' · ');
}
function categoryLink(from, course, type) {
  const entries = course.resources[type] || [];
  return entries.length ? link(from, `${entries.length} 个入口`, course.dashboard + '#' + type) : '—';
}

for (const course of catalog.courses) {
  if (ids.has(course.id)) problems.push(`重复课程 id：${course.id}`);
  ids.add(course.id);
  if (!fs.existsSync(path.join(root, course.directory))) problems.push(`课程目录不存在：${course.directory}`);
  for (const number of course.semesters) {
    if (!catalog.semesters.some(s => s.number === number)) problems.push(`未知学期：${course.id} / ${number}`);
  }
  for (const [type, entries] of Object.entries(course.resources)) {
    if (!(type in sections)) problems.push(`未知资料类型：${course.id} / ${type}`);
    for (const entry of entries) {
      if (!entry.label || !safePath(entry.path)) problems.push(`无效资源：${course.id} / ${entry.path}`);
      else if (!fs.existsSync(path.join(root, entry.path))) problems.push(`资源不存在：${entry.path}`);
    }
  }
  const from = course.dashboard;
  const available = Object.keys(sections).filter(k => course.resources[k]?.length);
  const nav = available.map(k => `[${sections[k]}](#${k})`).join(' · ');
  let body = `# ${course.title}\n\n${course.ru}\n\n${link(from, '课程总览', 'navigation/courses.md')} · ${semesterLinks(from, course)} · ${link(from, '知识索引', 'knowledge/index.md')}\n\n## 课程概况\n\n- 学期：${course.semesters.join('、')}。${course.kind ? `课程方向：${course.kind}。` : ''}\n- 资料状态：下方仅表示仓库可访问的资料，实验提交、验收和考试状态由本人确认。\n- ${course.note}\n\n${nav}\n`;
  for (const [key, heading] of Object.entries(sections)) {
    const entries = course.resources[key] || [];
    if (!entries.length) continue;
    body += `\n## ${heading} <a id="${key}"></a>\n\n` + entries.map(e => `- ${link(from, e.label, e.path)}`).join('\n') + '\n';
  }
  body += `\n## 学习与关联\n\n- ${link(from, '实验答辩：说明问题、核心实现和证据', 'study/defense.md')}\n- ${link(from, '考前复习：完整资料 → 口头回答 → 回到实现', 'study/revision.md')}\n`;
  if (course.related?.length) body += '- 关联课程：' + course.related.map(id => {
    const related = catalog.courses.find(c => c.id === id);
    if (!related) { problems.push(`关联课程不存在：${course.id} → ${id}`); return id; }
    return link(from, related.title, related.dashboard);
  }).join(' · ') + '\n';
  body += `- ${link(from, '原始目录与其他文件', course.directory)}；原始笔记与代码继续保留原路径。\n`;
  save(from, body);
}

for (const semester of catalog.semesters) {
  const from = `academic/semester-${String(semester.number).padStart(2, '0')}.md`;
  const courses = catalog.courses.filter(c => c.semesters.includes(semester.number));
  const previous = catalog.semesters.find(s => s.number === semester.number - 1);
  const next = catalog.semesters.find(s => s.number === semester.number + 1);
  const adjacent = [link(from, '学期总览', 'navigation/index.md'), previous && link(from, '上一学期', `academic/semester-${String(previous.number).padStart(2, '0')}.md`), next && link(from, '下一学期', `academic/semester-${String(next.number).padStart(2, '0')}.md`)].filter(Boolean).join(' · ');
  const rows = courses.map(c => `| ${link(from, c.title, c.dashboard)} | ${c.ru} | ${c.assessments?.[semester.number] || '见课程资料'} | ${categoryLink(from, c, 'labs')} | ${categoryLink(from, c, 'exam')} |`).join('\n');
  save(from, `# 第 ${semester.number} 学期 · ${semester.title}\n\n${adjacent}\n\n${semester.period} · 大${semester.year === 1 ? '一' : semester.year === 2 ? '二' : '三'}。本页 ${courses.length} 门课程已有仓库资料。\n\n课程归属和考核类型依据本人提供的第 1–5 学期教务截图；截图中仓库未收录的学科不建页面。跨学期课程共用资料，入口数量不代表该学期完成量。\n\n| 课程 | Русское название | 考核类型 | 实验 / 作业 | 考试资料 |\n|---|---|---|---|---|\n${rows}\n\n${link(from, '本学期考前复习入口', 'study/revision.md')} · ${link(from, '实验答辩入口', 'study/defense.md')}\n\n未保存成绩、考试日期或教务截图；不据此推断课程验收结果。`);
}

const overview = 'navigation/index.md';
save(overview, `# 学期导航 · Учебные семестры\n\n${link(overview, '首页', 'README.md')} · ${link(overview, '全部课程', 'navigation/courses.md')}\n\n| 学年 | 学期 | 时间 | 已有资料课程 |\n|---|---|---|---|\n${catalog.semesters.map(s => `| 第 ${s.year} 学年 | ${link(overview, `第 ${s.number} 学期 · ${s.title}`, `academic/semester-${String(s.number).padStart(2, '0')}.md`)} | ${s.period} | ${catalog.courses.filter(c => c.semesters.includes(s.number)).length} |`).join('\n')}\n\n学期以教务截图为准，当前覆盖第 1–5 学期；不预建后续学期或没有资料的课程。课程原目录不按学期搬迁，共用课程保持同一入口。\n\n${link(overview, '维护规则与标签', 'navigation/maintenance.md')} · ${link(overview, '知识地图', 'knowledge/index.md')}`);
const all = 'navigation/courses.md';
save(all, `# 课程总览 · Курсы\n\n${link(all, '首页', 'README.md')} · ${link(all, '按学期浏览', 'navigation/index.md')} · ${link(all, '知识索引', 'knowledge/index.md')}\n\n共 ${catalog.courses.length} 个课程入口；同一课程跨学期只维护一个 Dashboard。下面统计的是导航入口，不是已完成实验数；“—”表示目前未配置该类资料入口。\n\n| 课程 | 学期 | 理论 | 实验 / 作业 | 答辩 | 考试 |\n|---|---|---|---|---|---|\n${catalog.courses.map(c => `| ${link(all, c.title, c.dashboard)} | ${c.semesters.join('、')} | ${categoryLink(all, c, 'theory')} | ${categoryLink(all, c, 'labs')} | ${categoryLink(all, c, 'defense')} | ${categoryLink(all, c, 'exam')} |`).join('\n')}\n\n## 补充学习\n\n${link(all, 'Java 基础与练习', 'Java/Note.md')} · ${link(all, 'Java 专题', 'Java/subtopi.md')} · ${link(all, 'Go 源码', 'Go')} · ${link(all, '预科数学语言', 'MathsLanguage/keyknowledge.md')} · ${link(all, 'Blender 资源', 'Blender')} · ${link(all, 'Helios 使用', 'helios.md')}\n\n这些是已有辅助资料，未强行归入截图中的独立课程。`);
const labs = 'navigation/labs.md';
save(labs, `# 实验与作业索引 · Практические работы\n\n${link(labs, '首页', 'README.md')} · ${link(labs, '答辩指南', 'study/defense.md')}\n\n编号按原目录保留；“有说明”“有代码”“有报告”均不等于教师已验收。数学统计 РГР、语言练习、演示作业也在此收录。\n\n${catalog.courses.filter(c => c.resources.labs?.length).map(c => `## ${c.title}\n\n${link(labs, '课程入口', c.dashboard)}\n\n${c.resources.labs.map(e => `- ${link(labs, e.label, e.path)}`).join('\n')}`).join('\n\n')}`);

for (const file of outputs.keys()) {
  if (!assertNoSymlink(file)) continue;
  const absolute = path.join(root, file);
  if (fs.existsSync(absolute) && (!fs.statSync(absolute).isFile() || !fs.readFileSync(absolute, 'utf8').startsWith(generated))) {
    problems.push(`拒绝覆盖原始文件（缺少生成标记）：${file}`);
  }
}
if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
for (const [file, body] of outputs) {
  const absolute = path.join(root, file);
  if (check) {
    if (!fs.existsSync(absolute) || fs.readFileSync(absolute, 'utf8') !== body) problems.push(`需要重新生成：${file}`);
  } else {
    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    fs.writeFileSync(absolute, body);
  }
}
if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
console.log(`${check ? '已验证' : '已生成'} ${outputs.size} 个导航页；${catalog.courses.length} 门课程，${catalog.semesters.length} 个学期。`);
